# Règles d'alerte pour DBC B2B Platform
groups:
  - name: dbc_application_alerts
    rules:
      # Application down
      - alert: ApplicationDown
        expr: up{job=~"dbc-.*"} == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "DBC Application is down"
          description: "{{ $labels.job }} has been down for more than 1 minute."

      # Health check failing
      - alert: HealthCheckFailing
        expr: dbc_health_status != 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "DBC Health check failing"
          description: "Application health check has been failing for more than 2 minutes."

      # High error rate
      - alert: HighErrorRate
        expr: rate(dbc_http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second."

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(dbc_http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time"
          description: "95th percentile response time is {{ $value }}s."

      # Database connection issues
      - alert: DatabaseConnectionError
        expr: dbc_database_connection_errors_total > 10
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection errors"
          description: "{{ $value }} database connection errors in the last 2 minutes."

  - name: dbc_business_alerts
    rules:
      # Low order volume (business metric)
      - alert: LowOrderVolume
        expr: rate(dbc_orders_created_total[1h]) < 0.01
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Low order volume"
          description: "Order creation rate is {{ $value }} orders per second (less than expected)."

      # Failed catalog imports
      - alert: CatalogImportFailures
        expr: rate(dbc_catalog_import_failures_total[1h]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Catalog import failures"
          description: "{{ $value }} catalog import failures in the last hour."

      # High cart abandonment
      - alert: HighCartAbandonment
        expr: (dbc_carts_created_total - dbc_orders_created_total) / dbc_carts_created_total > 0.8
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High cart abandonment rate"
          description: "Cart abandonment rate is {{ $value }}%."

  - name: dbc_infrastructure_alerts
    rules:
      # High memory usage
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / process_virtual_memory_max_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%."

      # High CPU usage
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%."

      # Disk space low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value }}% full."
